### ISSUE TITLE
Add option for deconvolution

### ISSUE THREAD

**Issue by adam-azarchs** [Finalfantasykid/AstraStack#19]
First of all, this project is great - exactly what I was looking for as an open source alternative to AutoStakkert / Registax.

There's a couple of things that I think could be added in to make it more powerful, starting with an option to perform a deconvolution on the result image to address image quality issues in the telescope optics, such as imperfect focus, diffraction artifacts, or even motion blur from over-long exposures of individual frames.

OpenCV provides a pretty stright-forward [example script](https://github.com/opencv/opencv/blob/master/samples/python/deconvolution.py) for using [`cv.idft`](https://docs.opencv.org/4.5.0/d2/de8/group__core__array.html#gaa708aa2d2e57a508f968eb0f69aa5ff1) to preform a [Wiener deconvolution](https://en.wikipedia.org/wiki/Wiener_deconvolution).  The simplest implementation would have the user provide an assumed PSF, likely in the form of a radius for a gaussian blur.  A (much) fancier approach, which would be totally fair to declare out of scope for this project, would have the user photograph a star nearby to the planet of interest and use that image as the source for the PSF.  They'd probably need to use an image stack there as well to avoid the computed PSF being mostly noise.

If you think this would be a useful addition, I may have some time to provide some help with implementation.

**Comment by Finalfantasykid** [comment]
Hey thanks for trying this out.  I haven't looked into deconvolution before, I'm not exactly an image processing expert, just sort of learning as I go, but it might be something I could look into for the future.

**Comment by Finalfantasykid** [comment]
I added a branch for this feature https://github.com/Finalfantasykid/AstraStack/tree/deconvolution.  I was able to add some of the sample code you linked to, and get something which seems to be working for some sample images I have found online.  But I need to experiment some more with the parameters.

**Comment by Finalfantasykid** [comment]
@adam-azarchs I think I've gotten the deconvolution working pretty well.  I have a number of options for various types of PSFs.  If you are able to test out the code on the deconvolution branch to see if it is working the way you were expecting then that would be great.  I still need to update the Manual, but I think the actual functionality might be done, or close to done.

**Comment by adam-azarchs** [comment]
Thanks!  I probably won't have a chance to check it out before next weekend - my work schedule suddenly became very full, but looking forward to giving it a try.

**Comment by Finalfantasykid** [comment]
I released version 2.1.0 which has the deconvolution feature.  I think it is working quite well, so I'll close this for now, but feel free to re-open if something isn't working right.
